# Generated by Django 3.1.12 on 2025-03-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('customerId', models.IntegerField()),
                ('roomId', models.IntegerField(blank=True, null=True)),
                ('checkInDate', models.DateTimeField()),
                ('paymentStatus', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20)),
                ('Advance', models.FloatField()),
                ('Rent', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bookingsTable',
            },
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('serviceId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingId', models.IntegerField()),
                ('serviceName', models.CharField(max_length=100)),
                ('serviceCost', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'extraServices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingId', models.IntegerField()),
                ('amount', models.FloatField()),
                ('paymentMethod', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('UPI', 'UPI'), ('Online', 'Online')], max_length=50)),
                ('transactionId', models.CharField(max_length=100, unique=True)),
                ('paymentStatus', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('paymentType', models.CharField(blank=True, max_length=50, null=True)),
                ('serviceId', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paymentsTable',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refundId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingId', models.IntegerField()),
                ('refundAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('processedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refundsTable',
            },
        ),
        migrations.CreateModel(
            name='RoomInspection',
            fields=[
                ('inspectionId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingId', models.IntegerField()),
                ('roomCondition', models.TextField(max_length=50)),
                ('damageCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roomInspectionTable',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.IntegerField(unique=True)),
                ('roomNumber', models.CharField(max_length=10, unique=True)),
                ('roomType', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('Advance', models.FloatField()),
                ('Rent', models.FloatField()),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
