# Generated by Django 3.1.7 on 2025-04-10 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiRoleController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_controller', to='hotel_app.staffmanagement')),
                ('staffRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role', to='hotel_app.maintenancestaffroles')),
            ],
        ),
    ]
