# Generated by Django 3.1.12 on 2025-03-07 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('customerId', models.IntegerField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('complaint', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customerFeedback',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoiceId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingId', models.IntegerField()),
                ('invoiceNumber', models.CharField(max_length=100, unique=True)),
                ('roomCharge', models.FloatField()),
                ('extraServices', models.FloatField(blank=True, null=True)),
                ('taxes', models.FloatField(blank=True, null=True)),
                ('totalAmount', models.FloatField()),
                ('amountPaid', models.FloatField()),
                ('pendingAmount', models.FloatField(blank=True, null=True)),
                ('paymentMode', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('UPI', 'UPI'), ('Online', 'Online')], max_length=50)),
                ('transactionId', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoicesTable',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAssignment',
            fields=[
                ('assignmentId', models.AutoField(primary_key=True, serialize=False)),
                ('requestId', models.IntegerField()),
                ('staffId', models.IntegerField(blank=True, null=True)),
                ('assignedDate', models.DateTimeField(auto_now_add=True)),
                ('completionDate', models.DateTimeField(blank=True, null=True)),
                ('issueResolved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maintenanceAssignments',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('roomId', models.IntegerField()),
                ('issueDescription', models.TextField()),
                ('priorityLevel', models.CharField(max_length=20)),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'maintenanceRequests',
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('roomId', models.IntegerField()),
                ('guestName', models.CharField(max_length=100)),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('assignedBy', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'roomBooking',
            },
        ),
        migrations.CreateModel(
            name='RoomMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.IntegerField()),
                ('roomNumber', models.CharField(max_length=10)),
                ('maintenanceRequired', models.BooleanField()),
                ('lastCleanedDate', models.DateField(blank=True, null=True)),
                ('nextMaintenanceDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roomMaintenance',
            },
        ),
        migrations.CreateModel(
            name='RoomReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalRooms', models.IntegerField()),
                ('occupiedRooms', models.IntegerField()),
                ('roomsUnderMaint', models.IntegerField()),
                ('revenueByType', models.FloatField()),
            ],
            options={
                'db_table': 'roomReports',
            },
        ),
    ]


