# Generated by Django 3.1.12 on 2025-03-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_customerfeedback_invoices_maintenanceassignment_maintenancerequest_roombooking_roommaintenance_roomr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceStaffRequest',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('roomNumber', models.IntegerField()),
                ('issueType', models.CharField(max_length=50)),
                ('issueDescription', models.TextField()),
                ('reportedBy', models.CharField(max_length=50)),
                ('requestDateTime', models.DateTimeField(auto_now_add=True)),
                ('assignedStaff', models.IntegerField(blank=True, null=True)),
                ('taskStatus', models.CharField(default='Pending', max_length=20)),
                ('completionDateTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maintenanceStaffRequests',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('issueType', models.CharField(max_length=50)),
                ('priorityLevel', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('assignedStaff', models.IntegerField(blank=True, null=True)),
                ('assignmentDate', models.DateTimeField(auto_now_add=True)),
                ('taskStatus', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'maintenanceTasks',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTracking',
            fields=[
                ('taskId', models.IntegerField(primary_key=True, serialize=False)),
                ('roomNumber', models.IntegerField()),
                ('issueType', models.CharField(max_length=50)),
                ('assignedStaff', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('completionNotes', models.TextField(blank=True, null=True)),
                ('completionDateTime', models.DateTimeField(blank=True, null=True)),
                ('recurringIssuesCount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'maintenanceTracking',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusUpdate',
            fields=[
                ('taskId', models.IntegerField(primary_key=True, serialize=False)),
                ('assignedStaff', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('completionNotes', models.TextField(blank=True, null=True)),
                ('completionDateTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taskStatusUpdates',
            },
        ),
    ]
