# Generated by Django 3.1.7 on 2025-04-22 06:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_multirolecontroller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('checkoutId', models.AutoField(primary_key=True, serialize=False)),
                ('roomNo', models.CharField(max_length=20)),
                ('roomType', models.CharField(max_length=50)),
                ('checkinDate', models.DateField()),
                ('checkinTime', models.TimeField()),
                ('extraserviceTotalAmount', models.FloatField(default=0.0)),
                ('extraserviceAlreadyPaid', models.FloatField(default=0.0)),
                ('extraservicePendingAmount', models.FloatField(default=0.0)),
                ('checkoutDate', models.DateField()),
                ('checkoutTime', models.TimeField()),
                ('totalRentToBePaid', models.FloatField(default=0.0)),
                ('checkinAdvance', models.FloatField(default=0.0)),
                ('balanceRent', models.FloatField(default=0.0)),
                ('damageCost', models.FloatField(default=0.0)),
                ('discount', models.CharField(blank=True, help_text='Enter % (e.g., 10%) or amount (e.g., 500)', max_length=20, null=True)),
                ('stateGST', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('centralGST', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('totalAmountToBePaid', models.FloatField(default=0.0)),
                ('finalAmount', models.FloatField(default=0.0)),
                ('paymentStatus', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('paymentMethod', models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('UPI', 'UPI'), ('Online', 'Online')], max_length=50, null=True)),
                ('paymentType', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentDate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'checkout',
            },
        ),
        migrations.CreateModel(
            name='ExtraServiceCategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'extraServiceCategories',
            },
        ),
        migrations.RenameField(
            model_name='extraservice',
            old_name='serviceName',
            new_name='serviceDetails',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='amountPaid',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='extraServices',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='roomCharge',
        ),
        migrations.AddField(
            model_name='payment',
            name='centralGST',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentRemarks',
            field=models.CharField(blank=True, choices=[('Check-in Advance', 'Check-in Advance'), ('Extra Service', 'Extra Service'), ('Checkout', 'Checkout')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stateGST',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='totalAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('taxId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Rent', 'Rent'), ('Extra Service', 'Extra Service')], max_length=20)),
                ('stateGST', models.DecimalField(decimal_places=2, help_text='State GST in percentage', max_digits=5)),
                ('centralGST', models.DecimalField(decimal_places=2, help_text='Central GST in percentage', max_digits=5)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.extraservicecategory')),
            ],
            options={
                'db_table': 'taxes',
            },
        ),
        migrations.AddField(
            model_name='extraservice',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.extraservicecategory'),
        ),
    ]
