# Generated by Django 3.1.12 on 2025-03-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_maintenancestaffrequest_maintenancetask_maintenancetracking_taskstatusupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paymentStatus',
        ),
    ]
