# Generated by Django 3.1.7 on 2025-05-03 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_auto_20250503_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancestaffroles',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancestaffroles',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to='hotel_app.user'),
        ),
        migrations.AddField(
            model_name='maintenancestaffroles',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancestaffroles',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_roles', to='hotel_app.user'),
        ),
    ]
