# Generated by Django 3.1.7 on 2025-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_auto_20250426_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
