# Generated by Django 3.1.12 on 2025-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_remove_booking_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
