# Generated by Django 3.1.7 on 2025-04-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_payment_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkInTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
