# Generated by Django 3.1.12 on 2025-03-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_auto_20250308_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('idPassportNumber', models.CharField(max_length=100, unique=True)),
                ('contactNumber', models.CharField(max_length=20)),
                ('emailAddress', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('specialRequests', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customersTable',
            },
        ),
    ]
