# Generated by Django 3.1.12 on 2025-03-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('UPI', 'UPI'), ('Online', 'Online')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transactionId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
