# Generated by Django 3.1.12 on 2025-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0008_auto_20250310_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transactionId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
