# Generated by Django 3.1.7 on 2025-05-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0008_auto_20250503_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImageProof', to='hotel_app.customer')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
