# Generated by Django 3.1.12 on 2025-03-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_auto_20250310_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentStatus',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
    ]
