# Generated by Django 3.1.12 on 2025-03-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0010_auto_20250311_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraservice',
            name='paymentStatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=15),
        ),
    ]
