# Generated by Django 3.1.12 on 2025-03-13 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0011_extraservice_paymentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominspection',
            name='damageCharges',
        ),
        migrations.AddField(
            model_name='payment',
            name='inspectionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.roominspection'),
        ),
        migrations.AddField(
            model_name='roominspection',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roominspection',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='roominspection',
            name='roomCondition',
            field=models.CharField(choices=[('Good', 'Good'), ('Need Cleaning', 'Need Cleaning'), ('Damages', 'Damages')], max_length=50),
        ),
    ]
